name: Trigger auto deployment for pathwise-mentorship-server

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/pathwise-mentorship-server-AutoDeployTrigger-2640c385-78f0-470b-8d56-c780cbe67691.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.PATHWISEMENTORSHIPSERVER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PATHWISEMENTORSHIPSERVER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PATHWISEMENTORSHIPSERVER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.PATHWISEMENTORSHIPSERVER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PATHWISEMENTORSHIPSERVER_REGISTRY_PASSWORD }}
          containerAppName: pathwise-mentorship-server
          resourceGroup: Learning-Technical
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


