name: Daily MongoDB to Google Sheets Sync

on:
  schedule:
    # Run daily at 9:00 AM UTC (4:00 AM EST, 1:00 AM PST)
    # Adjust the hour (9) to your preferred UTC time
    - cron: "0 9 * * *"
  workflow_dispatch: # Allow manual trigger

jobs:
  sync-to-sheets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Validate environment variables
        run: |
          echo "Checking environment variables..."
          echo "MONGO_URI length: ${#MONGO_URI}"
          echo "GOOGLE_SPREADSHEET_ID length: ${#GOOGLE_SPREADSHEET_ID}"
          echo "GOOGLE_SHEET_NAME length: ${#GOOGLE_SHEET_NAME}"
          echo "GOOGLE_SERVICE_ACCOUNT_KEY length: ${#GOOGLE_SERVICE_ACCOUNT_KEY}"
          echo "First 50 chars of service key: ${GOOGLE_SERVICE_ACCOUNT_KEY:0:50}..."
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          GOOGLE_SPREADSHEET_ID: ${{ secrets.GOOGLE_SPREADSHEET_ID }}
          GOOGLE_SHEET_NAME: ${{ secrets.GOOGLE_SHEET_NAME }}
          GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}

      - name: Run MongoDB to Google Sheets sync
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          GOOGLE_SPREADSHEET_ID: ${{ secrets.GOOGLE_SPREADSHEET_ID }}
          GOOGLE_SHEET_NAME: ${{ secrets.GOOGLE_SHEET_NAME }}
          GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
        run: npm run sync-sheets

      - name: Notify on success
        if: success()
        run: echo "✅ MongoDB to Google Sheets sync completed successfully!"

      - name: Notify on failure
        if: failure()
        run: echo "❌ MongoDB to Google Sheets sync failed!"
